stages:
    - test
    - build
    - deploy

pages:
    stage: deploy
    script:
        - mkdir .public
        - sbcl --load staple-generate.lisp --disable-debugger --quit
        - cp -r ./doc/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master

image : daewok/lisp-devel

before_script:
    - apt-get update -qy
    - apt-get install -y git-core
    - git clone https://github.com/Shinmera/parachute.git ~/quicklisp/local-projects/parachute
    - ln -s "${CI_PROJECT_DIR}" ~/quicklisp/local-projects/method-hooks
    

test-sbcl:
    stage: test
    script:
         - sbcl --load ci-test.lisp --disable-debugger --quit

test-ccl:
    stage: test
    script:
        - ccl --load ci-test.lisp